services:
    app.friend.listener:
        class: AppBundle\EntityListener\SlugListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
        arguments:
            - "@app.slug"
