services:
    app.security.authentication_rest_handler:
        class: AppBundle\Handler\AuthenticationRestHandler
        arguments: ['@doctrine.orm.entity_manager']

    app.slug:
        class: AppBundle\Service\SlugService
        arguments:
            - '@slugify'

    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']

